### ISSUE TITLE
Application does not work

### ISSUE THREAD

**Issue by JosedeKruif** [jlonij/frame-generator#1]
I was curious about frame-generator. Tried several uploads (txt files). Frame-generator returns: "Error processing document".

**Comment by JosedeKruif** [comment]
Tried with a file of 24 KB and it worked fine! Thanks. But a file of 25kb I can read myself and establish frames. What happens if I upload, say,  20 files of 25 KB?

**Comment by jlonij** [comment]
The web interface at http://www.kbresearch.nl/frames/ currently limits the upload size to 25 KB (for all files combined) because of the significant processing capacity required to calculate the frames. It is only intended to provide a quick impression of the main functionality of the Frame Generator. The command line tool and GUI source code available here on GitHub can be used for processing larger data sets on a local machine.

**Comment by JosedeKruif** [comment]
O.K. Thank you very much. I will try this very interesting tool on a local machine next week and then use larger data sets. I can report back again on the results if you would like that.

**Comment by jlonij** [comment]
I'm closing this particular issue, but would be happy to hear about your results or any questions you might have. We are still working on proper documentation for this tool, which will be available for the launch of the new KB Lab website (expected this April) at the latest.
